import {
  createDirectory,
  writeFile,
  getProjectPath,
  logInfo,
  initializeGit,
  capitalize,
  getPackageManagerRunCmd,
  getPackageManagerInstallCmd,
  type GeneratorConfig,
} from "@/utils/helpers.js";
import { generateElysiaBackend } from "@/generators/backends/elysia.js";
import { generateFastAPIBackend } from "@/generators/backends/fastapi.js";
import { generateNestJSBackend } from "@/generators/backends/nestjs.js";
import { generateAstroFrontend } from "@/generators/frontends/astro.js";
import { generateSvelteFrontend } from "@/generators/frontends/svelte.js";
import { generateNextJSFrontend } from "@/generators/frontends/nextjs.js";
import { generateVueFrontend } from "@/generators/frontends/vue.js";
import { spinner } from "@clack/prompts";

export async function generateMonorepo(config: GeneratorConfig): Promise<void> {
  const projectPath = getProjectPath(config.projectName);
  const s = spinner();

  s.start(`Creating monorepo structure at ${projectPath}...`);
  await createDirectory(projectPath);

  s.message(`Creating workspace directories...`);
  const backendPath = `${projectPath}/${capitalize(config.projectName)}_Backend`;
  const frontendPath = `${projectPath}/${capitalize(config.projectName)}_Frontend`;
  const docsPath = `${projectPath}/Docs`;

  await createDirectory(backendPath);
  await createDirectory(frontendPath);
  await createDirectory(docsPath);

  s.message(`Generating configuration files...`);
  await generateGitIgnore(projectPath);
  await generateReadme(projectPath, config);
  await generateAgentsMd(projectPath, config);
  await generateLicense(projectPath, config);
  await generateEnvExample(projectPath);

  if (config.backend) {
    s.message(`Generating ${capitalize(config.backend.framework)} backend...`);
    switch (config.backend.framework) {
      case "elysia":
        await generateElysiaBackend(backendPath, config);
        break;
      case "fastapi":
        await generateFastAPIBackend(backendPath, config);
        break;
      case "nestjs":
        await generateNestJSBackend(backendPath, config);
        break;
    }
    s.stop(`✨ ${capitalize(config.backend.framework)} backend generated`);
    s.start();
  }

  if (config.frontend) {
    s.message(`Generating ${capitalize(config.frontend.framework)} frontend...`);
    switch (config.frontend.framework) {
      case "astro":
        await generateAstroFrontend(frontendPath, config);
        break;
      case "svelte":
        await generateSvelteFrontend(frontendPath, config);
        break;
      case "nextjs":
        await generateNextJSFrontend(frontendPath, config);
        break;
      case "vue":
        await generateVueFrontend(frontendPath, config);
        break;
    }
    s.stop(`✨ ${capitalize(config.frontend.framework)} frontend generated`);
    s.start();
  }

  s.message(`Creating documentation structure...`);
  await createDirectory(`${docsPath}/Feature`);
  await createDirectory(`${docsPath}/DatabaseSetup`);
  await generateSchemaDocs(docsPath, config);

  const backendName = `${capitalize(config.projectName)}_Backend`;
  const frontendName = `${capitalize(config.projectName)}_Frontend`;

  s.stop(`✨ Monorepo created at ${config.projectName}`);

  if (config.git) {
    await initializeGit(projectPath);
  }

  const backendInstallCmd = getPackageManagerInstallCmd(config.backend?.packageManager || "npm");
  const backendRunCmd = getPackageManagerRunCmd(config.backend?.packageManager || "npm", "dev");
  const frontendInstallCmd = getPackageManagerInstallCmd(config.frontend?.packageManager || "npm");
  const frontendRunCmd = getPackageManagerRunCmd(config.frontend?.packageManager || "npm", "dev");

  logInfo("\n📦 Next steps:");
  logInfo(`  cd ${config.projectName}`);
  logInfo(`  # Backend`);
  logInfo(`  cd ${backendName} && ${backendInstallCmd} && ${backendRunCmd}`);
  logInfo(`  # Frontend`);
  logInfo(`  cd ${frontendName} && ${frontendInstallCmd} && ${frontendRunCmd}`);
}

async function generateGitIgnore(projectPath: string): Promise<void> {
  const content = `# Dependencies
node_modules/
.pnp
.pnp.js

# Testing
coverage/
*.lcov

# Next.js
.next/
out/

# Production
build/
dist/

# Misc
.DS_Store
*.pem

# Debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Local env files
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Vercel
.vercel

# TypeScript
*.tsbuildinfo

# IDE
.idea/
.vscode/
*.swp
*.swo
*~
`;

  await writeFile(`${projectPath}/.gitignore`, content);
}

async function generateReadme(projectPath: string, config: GeneratorConfig): Promise<void> {
  const backendName = `${capitalize(config.projectName)}_Backend`;
  const frontendName = `${capitalize(config.projectName)}_Frontend`;

  const content = `# ${config.projectName}

This project was generated by [Phos](https://github.com/yourusername/phos).

## Project Structure

\`\`\`
.
├── ${backendName}/     # ${config.backend?.framework} backend
├── ${frontendName}/    # ${config.frontend?.framework} frontend
├── Docs/               # Documentation
├── AGENTS.md           # Agent guidelines
├── LICENSE             # License file
└── env.example         # Environment variables template
\`\`\`

## Getting Started

### Backend

\`\`\`bash
cd ${backendName}
${config.backend?.packageManager} install
${config.backend?.packageManager} run dev
\`\`\`

### Frontend

\`\`\`bash
cd ${frontendName}
${config.frontend?.packageManager} install
${config.frontend?.packageManager} run dev
\`\`\`

## Available Scripts

- \`${config.frontend?.packageManager} run dev\` - Start development servers
- \`${config.frontend?.packageManager} run build\` - Build for production
- \`${config.frontend?.packageManager} run lint\` - Run ESLint
- \`${config.frontend?.packageManager} run format\` - Format code with Prettier

## Tech Stack

### Backend
- Framework: ${config.backend?.framework}
- Package Manager: ${config.backend?.packageManager}
- TypeScript: ${config.backend?.typescript ? "Yes" : "No"}
- ESLint: ${config.backend?.eslint ? "Yes" : "No"}
- Prettier: ${config.backend?.prettier ? "Yes" : "No"}

### Frontend
- Framework: ${config.frontend?.framework}
- Package Manager: ${config.frontend?.packageManager}
- TypeScript: ${config.frontend?.typescript ? "Yes" : "No"}
- ESLint: ${config.frontend?.eslint ? "Yes" : "No"}
- Prettier: ${config.frontend?.prettier ? "Yes" : "No"}
- CSS Framework: ${config.frontend?.cssFramework}
- UI Components: ${config.frontend?.uiComponents}
- Testing: ${config.frontend?.testing}
`;

  await writeFile(`${projectPath}/README.md`, content);
}

async function generateAgentsMd(projectPath: string, config: GeneratorConfig): Promise<void> {
  const projectName = config.projectName;
  const capitalizedProjectName = capitalize(config.projectName);
  const backendName = `${capitalizedProjectName}_Backend`;
  const frontendName = `${capitalizedProjectName}_Frontend`;

  const content = `# AGENTS Guidelines for This Repository

## Project Name: ${projectName}

This project was generated by [Phos](https://github.com/yourusername/phos).

### Core Features:

1. **${config.frontend?.framework || "Next.js"} Frontend** - Modern web framework
2. **${config.backend?.framework || "Elysia"} Backend** - Server-side application
3. **Monorepo Structure** - Organized workspace with separate backend and frontend

### Technology Stack:

- **Frontend**: ${config.frontend?.framework || "Next.js"}
- **Backend**: ${config.backend?.framework || "Elysia"}
- **Package Manager**: ${config.frontend?.packageManager || "npm"}
- **TypeScript**: ${config.frontend?.typescript ? "Enabled" : "Disabled"}
- **ESLint**: ${config.frontend?.eslint ? "Enabled" : "Disabled"}
- **Prettier**: ${config.frontend?.prettier ? "Enabled" : "Disabled"}
- **CSS Framework**: ${config.frontend?.cssFramework || "Tailwind CSS"}

## 1. Development Workflow

### Project Structure

\`\`\`
${projectName}/
├── ${backendName}/    # Backend application
├── ${frontendName}/   # Frontend application
├── Docs/                             # Documentation
├── AGENTS.md                         # This file
├── LICENSE                           # License
├── README.md                         # Project README
└── env.example                       # Environment variables template
\`\`\`

### Running the Project

#### Backend
\`\`\`bash
cd ${backendName}
${config.backend?.packageManager || "npm"} install
${config.backend?.packageManager || "npm"} run dev
\`\`\`

#### Frontend
\`\`\`bash
cd ${frontendName}
${config.frontend?.packageManager || "npm"} install
${config.frontend?.packageManager || "npm"} run dev
\`\`\`

## 2. Architecture

### Backend
- Framework: ${config.backend?.framework || "Elysia"}
- Language: ${config.backend?.framework === "fastapi" ? "Python" : "TypeScript"}
- Package Manager: ${config.backend?.packageManager || "npm"}

### Frontend
- Framework: ${config.frontend?.framework || "Next.js"}
- Language: JavaScript/TypeScript
- Package Manager: ${config.frontend?.packageManager || "npm"}
- CSS Framework: ${config.frontend?.cssFramework || "Tailwind CSS"}
- UI Components: ${config.frontend?.uiComponents || "None"}

## 3. Coding Conventions

### ${config.frontend?.framework || "Next.js"}

${
  config.frontend?.framework === "astro"
    ? `
- Use Astro component syntax
- Follow Astro best practices
- Use TypeScript if enabled
`
    : config.frontend?.framework === "svelte"
      ? `
- Use Svelte component syntax
- Follow Svelte best practices
- Use TypeScript if enabled
`
      : config.frontend?.framework === "vue"
        ? `
- Use Vue 3 Composition API
- Follow Vue best practices
- Use TypeScript if enabled
`
        : `
- Use Next.js conventions
- Use App Router for new features
- Use TypeScript if enabled
`
}

### ${config.backend?.framework || "Elysia"}

${
  config.backend?.framework === "elysia"
    ? `
- Use Elysia patterns
- Follow Bun conventions
- Use TypeScript if enabled
`
    : `
- Use FastAPI patterns
- Follow Python PEP 8 guidelines
- Use type hints
`
}

## 4. Available Scripts

### Root Level
- \`${config.frontend?.packageManager || "npm"} run dev\` - Start both dev servers
- \`${config.frontend?.packageManager || "npm"} run build\` - Build both apps
- \`${config.frontend?.packageManager || "npm"} run lint\` - Run ESLint
- \`${config.frontend?.packageManager || "npm"} run format\` - Format code

## 5. Documentation

Check the \`Docs/\` folder for:
- Feature documentation
- Database setup scripts
- Schema documentation
- SQL queries
`;

  await writeFile(`${projectPath}/AGENTS.md`, content);
}

async function generateLicense(projectPath: string, config: GeneratorConfig): Promise<void> {
  const content = `MIT License

Copyright (c) ${new Date().getFullYear()} ${config.projectName}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
`;

  await writeFile(`${projectPath}/LICENSE`, content);
}

async function generateEnvExample(projectPath: string): Promise<void> {
  const content = `# Database
DB_HOST=localhost
DB_NAME=your_db_name
DB_USER=postgres
DB_PASSWORD=postgres
DB_PORT=5433

# URLs
FRONTEND_BASE_URL=http://localhost:4200
BACKEND_BASE_URL=http://localhost:4100

# JWT Configuration for rest API
JWT_SECRET=your-super-secret-jwt-key-change-in-production
JWT_EXPIRES_IN=60m

# Encryption
ENCRYPTION_SALT=your-super-secret-salt-change-in-production

# API Keys
X_API_KEY=1234
`;

  await writeFile(`${projectPath}/env.example`, content);
}

async function generateSchemaDocs(docsPath: string, config: GeneratorConfig): Promise<void> {
  const projectName = config.projectName;
  const content = `# ${projectName} Database Schema

## Table of Contents

- [${projectName} Database Schema](#${projectName.toLowerCase()}-database-schema)
  - [Table of Contents](#table-of-contents)
  - [Overview](#overview)
  - [Core Entities](#core-entities)
    - [Entity Name](#entity-name)
  - [Entity Relationships](#entity-relationships)
  - [SQL Schema](#sql-schema)
    - [Create Tables](#create-tables)
  - [Sample Data](#sample-data)
  - [Data Types Notes](#data-types-notes)
  - [Migration Notes](#migration-notes)

---

## Overview

This document describes the complete database schema for ${projectName}, including all entities, relationships, and sample data.

---

## Core Entities

### Entity Name

| Column      | Type     | Nullable | Description                        |
| ----------- | -------- | -------- | ---------------------------------- |
| id          | int      | No       | Primary key, auto-incremented ID   |
| uuid        | string   | No       | Unique identifier                  |
| column_name | str      | Yes/No   | Description of column              |
| created_at  | datetime | No       | Record creation timestamp (UTC)    |
| updated_at  | datetime | Yes      | Record last update timestamp (UTC) |

---

## Entity Relationships

\`\`\`
table1 (1) ──── (many) table2
table3 (many) ──── (1) table4
\`\`\`

---

## SQL Schema

### Create Tables

For PostgreSQL deployment, use the following schema:

\`\`\`sql
-- Drop tables if they exist (for clean setup)
DROP TABLE IF EXISTS child_table;
DROP TABLE IF EXISTS parent_table;

-- Parent table
CREATE TABLE parent_table (
    id SERIAL PRIMARY KEY,
    uuid TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- Child table
CREATE TABLE child_table (
    id TEXT PRIMARY KEY,
    parent_id TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (parent_id) REFERENCES parent_table(uuid)
);

-- Add foreign key constraints if needed
ALTER TABLE child_table ADD CONSTRAINT fk_child_parent FOREIGN KEY (parent_id) REFERENCES parent_table(uuid);

-- Performance indexes
CREATE INDEX idx_parent_table_uuid ON parent_table(uuid);
CREATE INDEX idx_child_table_parent_id ON child_table(parent_id);
CREATE INDEX idx_child_table_created_at ON child_table(created_at);
\`\`\`

---

## Sample Data

\`\`\`sql
-- Insert sample data for parent table
INSERT INTO parent_table (uuid, name, description, created_at)
VALUES ('550e8400-e29b-41d4-a716-446655440000', 'Sample Name', 'Sample description', CURRENT_TIMESTAMP);

-- Insert sample data for child table
INSERT INTO child_table (id, parent_id, content, created_at, updated_at)
VALUES ('6ba7b810-9dad-11d1-80b4-00c04fd430c8', '550e8400-e29b-41d4-a716-446655440000', 'Sample content', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
\`\`\`

---

## Data Types Notes

- **UUID**: Stored as TEXT for simplicity
- **Arrays**: Stored as native PostgreSQL arrays (e.g., text[])
- **JSON**: Stored as JSONB for PostgreSQL (or TEXT for SQLite)
- **Boolean**: Stored as BOOLEAN for PostgreSQL (or INTEGER 0/1 for SQLite)
- **Decimal**: Stored as DECIMAL for precision calculations
- **Datetime**: Stored as TIMESTAMP with CURRENT_TIMESTAMP defaults

---

## Migration Notes

When deploying to production:

1. Consider using PostgreSQL for better JSON support and performance
2. Add proper UUID generation in application code
3. Implement database migrations for schema changes
4. Add database constraints and triggers as needed
5. Run \`ALTER TABLE\` statements for schema additions
6. Test migrations on staging environment before production
`;

  await writeFile(`${docsPath}/Schema.md`, content);
}
