import {
  createDirectory,
  writeFile,
  getProjectPath,
  logStep,
  logSuccess,
  logInfo,
  initializeGit,
  capitalize,
  type GeneratorConfig,
} from "@/utils/helpers.js";
import { generateElysiaBackend } from "@/generators/backends/elysia.js";
import { generateFastAPIBackend } from "@/generators/backends/fastapi.js";
import { generateAstroFrontend } from "@/generators/frontends/astro.js";
import { generateSvelteFrontend } from "@/generators/frontends/svelte.js";
import { generateNextJSFrontend } from "@/generators/frontends/nextjs.js";

export async function generateMonorepo(config: GeneratorConfig): Promise<void> {
  const projectPath = getProjectPath(config.projectName);

  logStep(`Creating monorepo at ${projectPath}`);
  await createDirectory(projectPath);

  const backendPath = `${projectPath}/${capitalize(config.projectName)}_Backend`;
  const frontendPath = `${projectPath}/${capitalize(config.projectName)}_Frontend`;
  const docsPath = `${projectPath}/Docs`;

  await createDirectory(backendPath);
  await createDirectory(frontendPath);
  await createDirectory(docsPath);

  await generateGitIgnore(projectPath);
  await generateReadme(projectPath, config);
  await generateAgentsMd(projectPath, config);
  await generateLicense(projectPath, config);
  await generateEnvExample(projectPath);

  switch (config.backend.framework) {
    case "elysia":
      await generateElysiaBackend(backendPath, config);
      break;
    case "fastapi":
      await generateFastAPIBackend(backendPath, config);
      break;
  }

  switch (config.frontend.framework) {
    case "astro":
      await generateAstroFrontend(frontendPath, config);
      break;
    case "svelte":
      await generateSvelteFrontend(frontendPath, config);
      break;
    case "nextjs":
      await generateNextJSFrontend(frontendPath, config);
      break;
  }

  await createDirectory(`${docsPath}/Feature`);
  await createDirectory(`${docsPath}/DatabaseSetup`);
  await generateDocsReadme(docsPath);

  const backendName = `${capitalize(config.projectName)}_Backend`;
  const frontendName = `${capitalize(config.projectName)}_Frontend`;

  logSuccess(`Backend created at ${backendName}`);
  logSuccess(`Frontend created at ${frontendName}`);
  logSuccess("Docs folder created");

  if (config.git) {
    await initializeGit(projectPath);
  }

  logInfo("\n📦 Next steps:");
  logInfo(`  cd ${config.projectName}`);
  logInfo(`  # Backend`);
  logInfo(
    `  cd ${backendName} && ${config.backend.packageManager} install && ${config.backend.packageManager} run dev`
  );
  logInfo(`  # Frontend`);
  logInfo(
    `  cd ${frontendName} && ${config.frontend.packageManager} install && ${config.frontend.packageManager} run dev`
  );
}

async function generateGitIgnore(projectPath: string): Promise<void> {
  const content = `# Dependencies
node_modules/
.pnp
.pnp.js

# Testing
coverage/
*.lcov

# Next.js
.next/
out/

# Production
build/
dist/

# Misc
.DS_Store
*.pem

# Debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Local env files
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Vercel
.vercel

# TypeScript
*.tsbuildinfo

# IDE
.idea/
.vscode/
*.swp
*.swo
*~
`;

  await writeFile(`${projectPath}/.gitignore`, content);
  logSuccess(".gitignore created");
}

async function generateReadme(projectPath: string, config: GeneratorConfig): Promise<void> {
  const backendName = `${capitalize(config.projectName)}_Backend`;
  const frontendName = `${capitalize(config.projectName)}_Frontend`;

  const content = `# ${config.projectName}

This project was generated by [Phos](https://github.com/yourusername/phos).

## Project Structure

\`\`\`
.
├── ${backendName}/     # ${config.backend.framework} backend
├── ${frontendName}/    # ${config.frontend.framework} frontend
├── Docs/               # Documentation
├── AGENTS.md           # Agent guidelines
├── LICENSE             # License file
└── env.example         # Environment variables template
\`\`\`

## Getting Started

### Backend

\`\`\`bash
cd ${backendName}
${config.backend.packageManager} install
${config.backend.packageManager} run dev
\`\`\`

### Frontend

\`\`\`bash
cd ${frontendName}
${config.frontend.packageManager} install
${config.frontend.packageManager} run dev
\`\`\`

## Available Scripts

- \`${config.frontend.packageManager} run dev\` - Start development servers
- \`${config.frontend.packageManager} run build\` - Build for production
- \`${config.frontend.packageManager} run lint\` - Run ESLint
- \`${config.frontend.packageManager} run format\` - Format code with Prettier

## Tech Stack

### Backend
- Framework: ${config.backend.framework}
- Package Manager: ${config.backend.packageManager}
- TypeScript: ${config.backend.typescript ? "Yes" : "No"}
- ESLint: ${config.backend.eslint ? "Yes" : "No"}
- Prettier: ${config.backend.prettier ? "Yes" : "No"}

### Frontend
- Framework: ${config.frontend.framework}
- Package Manager: ${config.frontend.packageManager}
- TypeScript: ${config.frontend.typescript ? "Yes" : "No"}
- ESLint: ${config.frontend.eslint ? "Yes" : "No"}
- Prettier: ${config.frontend.prettier ? "Yes" : "No"}
- CSS Framework: ${config.frontend.cssFramework}
- UI Components: ${config.frontend.uiComponents}
- Testing: ${config.frontend.testing}
`;

  await writeFile(`${projectPath}/README.md`, content);
  logSuccess("README.md created");
}

async function generateAgentsMd(projectPath: string, config: GeneratorConfig): Promise<void> {
  const projectName = config.projectName;
  const capitalizedProjectName = capitalize(config.projectName);
  const backendName = `${capitalizedProjectName}_Backend`;
  const frontendName = `${capitalizedProjectName}_Frontend`;

  const content = `# AGENTS Guidelines for This Repository

## Project Name: ${projectName}

This project was generated by [Phos](https://github.com/yourusername/phos).

### Core Features:

1. **${config.frontend.framework} Frontend** - Modern web framework
2. **${config.backend.framework} Backend** - Server-side application
3. **Monorepo Structure** - Organized workspace with separate backend and frontend

### Technology Stack:

- **Frontend**: ${config.frontend.framework}
- **Backend**: ${config.backend.framework}
- **Package Manager**: ${config.frontend.packageManager}
- **TypeScript**: ${config.frontend.typescript ? "Enabled" : "Disabled"}
- **ESLint**: ${config.frontend.eslint ? "Enabled" : "Disabled"}
- **Prettier**: ${config.frontend.prettier ? "Enabled" : "Disabled"}
- **CSS Framework**: ${config.frontend.cssFramework}

## 1. Development Workflow

### Project Structure

\`\`\`
${projectName}/
├── ${backendName}/    # Backend application
├── ${frontendName}/   # Frontend application
├── Docs/                             # Documentation
├── AGENTS.md                         # This file
├── LICENSE                           # License
├── README.md                         # Project README
└── env.example                       # Environment variables template
\`\`\`

### Running the Project

#### Backend
\`\`\`bash
cd ${backendName}
${config.backend.packageManager} install
${config.backend.packageManager} run dev
\`\`\`

#### Frontend
\`\`\`bash
cd ${frontendName}
${config.frontend.packageManager} install
${config.frontend.packageManager} run dev
\`\`\`

## 2. Architecture

### Backend
- Framework: ${config.backend.framework}
- Language: ${config.backend.framework === "fastapi" ? "Python" : "TypeScript"}
- Package Manager: ${config.backend.packageManager}

### Frontend
- Framework: ${config.frontend.framework}
- Language: JavaScript/TypeScript
- Package Manager: ${config.frontend.packageManager}
- CSS Framework: ${config.frontend.cssFramework}
- UI Components: ${config.frontend.uiComponents}

## 3. Coding Conventions

### ${config.frontend.framework}

${
  config.frontend.framework === "astro"
    ? `
- Use Astro component syntax
- Follow Astro best practices
- Use TypeScript if enabled
`
    : config.frontend.framework === "svelte"
      ? `
- Use Svelte component syntax
- Follow Svelte best practices
- Use TypeScript if enabled
`
      : `
- Use Next.js conventions
- Use App Router for new features
- Use TypeScript if enabled
`
}

### ${config.backend.framework}

${
  config.backend.framework === "elysia"
    ? `
- Use Elysia patterns
- Follow Bun conventions
- Use TypeScript if enabled
`
    : `
- Use FastAPI patterns
- Follow Python PEP 8 guidelines
- Use type hints
`
}

## 4. Available Scripts

### Root Level
- \`${config.frontend.packageManager} run dev\` - Start both dev servers
- \`${config.frontend.packageManager} run build\` - Build both apps
- \`${config.frontend.packageManager} run lint\` - Run ESLint
- \`${config.frontend.packageManager} run format\` - Format code

## 5. Documentation

Check the \`Docs/\` folder for:
- Feature documentation
- Database setup scripts
- Schema documentation
- SQL queries
`;

  await writeFile(`${projectPath}/AGENTS.md`, content);
  logSuccess("AGENTS.md created");
}

async function generateLicense(projectPath: string, config: GeneratorConfig): Promise<void> {
  const content = `MIT License

Copyright (c) ${new Date().getFullYear()} ${config.projectName}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
`;

  await writeFile(`${projectPath}/LICENSE`, content);
  logSuccess("LICENSE created");
}

async function generateEnvExample(projectPath: string): Promise<void> {
  const content = `# Environment Variables Template
# Copy this file to .env and fill in the actual values

# Backend
BACKEND_PORT=3000
BACKEND_HOST=localhost

# Database
DATABASE_URL=postgresql://user:password@localhost:5432/database

# API Keys
API_KEY=your_api_key_here

# Frontend
VITE_API_URL=http://localhost:3000
`;

  await writeFile(`${projectPath}/env.example`, content);
  logSuccess("env.example created");
}

async function generateDocsReadme(docsPath: string): Promise<void> {
  const content = `# Documentation

This folder contains project documentation.

## Structure

- \`Feature/\` - Feature documentation
- \`DatabaseSetup/\` - Database setup scripts and migrations

## Adding Documentation

Add new feature documentation in the \`Feature/\` folder.
Add database scripts in the \`DatabaseSetup/\` folder.
`;

  await writeFile(`${docsPath}/README.md`, content);
  logSuccess("Docs README created");
}
