import { createDirectory, writeFile, logSuccess, type GeneratorConfig } from "@/utils/helpers.js";

export async function generateFastAPIBackend(
  projectPath: string,
  config: GeneratorConfig
): Promise<void> {
  const srcPath = `${projectPath}/src`;
  await createDirectory(srcPath);

  await generateIndexFile(srcPath, config);
  await generateRequirementsTxt(projectPath, config);
  await generatePyProject(projectPath, config);
  await generateReadme(projectPath, config);

  if (config.backend.eslint) {
    await generatePylintrc(projectPath);
  }

  if (config.backend.prettier) {
    await generatePyprojectToml(projectPath, config);
  }

  logSuccess(`FastAPI backend generated`);
}

async function generateIndexFile(srcPath: string, config: GeneratorConfig): Promise<void> {
  const content = `from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from datetime import datetime

app = FastAPI(
    title="${config.projectType === "monorepo" ? "Backend API" : config.projectName}",
    description="Generated by Phos",
    version="0.1.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
async def root():
    return {"message": "Hello from Phos! 🚀"}

@app.get("/api/hello")
async def hello():
    return {
        "message": "Hello from API!",
        "timestamp": datetime.now().isoformat()
    }

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
`;

  await writeFile(`${srcPath}/main.py`, content);
}

async function generateRequirementsTxt(
  projectPath: string,
  config: GeneratorConfig
): Promise<void> {
  const requirements = [
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.24.0",
    "pydantic>=2.0.0",
    "python-multipart>=0.0.6",
  ];

  if (config.backend.eslint) {
    requirements.push("pylint>=3.0.0");
  }

  if (config.backend.prettier) {
    requirements.push("black>=23.0.0");
  }

  await writeFile(`${projectPath}/requirements.txt`, requirements.join("\n"));
}

async function generatePyProject(projectPath: string, config: GeneratorConfig): Promise<void> {
  const content = `[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "${config.projectType === "monorepo" ? "backend" : config.projectName}"
version = "0.1.0"
description = "Generated by Phos"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.24.0",
    "pydantic>=2.0.0",
    "python-multipart>=0.0.6",
]

[tool.hatch.build.targets.wheel]
packages = ["src"]
`;

  await writeFile(`${projectPath}/pyproject.toml`, content);
}

async function generateReadme(projectPath: string, config: GeneratorConfig): Promise<void> {
  const content = `# FastAPI Backend

Generated by [Phos](https://github.com/yourusername/phos).

## Getting Started

\`\`\`bash
# Install dependencies
pip install -r requirements.txt

# Run development server
uvicorn src.main:app --reload --port 8000
\`\`\`

## API Documentation

Once the server is running, visit:
- Swagger UI: http://localhost:8000/docs
- ReDoc: http://localhost:8000/redoc

## Available Scripts

- \`uvicorn src.main:app --reload\` - Start development server
- \`uvicorn src.main:app\` - Start production server
${config.backend.eslint ? "- \`pylint src\` - Run linter\n" : ""}${config.backend.prettier ? "- \`black src\` - Format code\n" : ""}

## Tech Stack

- Framework: FastAPI
- Python: 3.10+
- ESLint: ${config.backend.eslint ? "Yes" : "No"}
- Prettier (Black): ${config.backend.prettier ? "Yes" : "No"}
`;

  await writeFile(`${projectPath}/README.md`, content);
}

async function generatePylintrc(projectPath: string): Promise<void> {
  const content = `[MASTER]
disable=C0114,C0115,C0116,W0611
`;

  await writeFile(`${projectPath}/.pylintrc`, content);
}

async function generatePyprojectToml(projectPath: string, config: GeneratorConfig): Promise<void> {
  if (!config.backend.prettier) return;

  const content = `[tool.black]
line-length = 88
target-version = ['py310']
include = '\\.pyi?$'
extend-exclude = '''
/(
  # directories
  \\.eggs
  | \\.git
  | \\.hg
  | \\.mypy_cache
  | \\.tox
  | \\.venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
`;

  await writeFile(`${projectPath}/pyproject.toml`, content);
}
