import { createDirectory, writeFile, logSuccess, type GeneratorConfig } from "@/utils/helpers.js";

export async function generateAstroFrontend(
  projectPath: string,
  config: GeneratorConfig
): Promise<void> {
  const srcPath = `${projectPath}/src`;
  await createDirectory(srcPath);
  await createDirectory(`${srcPath}/pages`);
  await createDirectory(`${srcPath}/components`);
  await createDirectory(`${srcPath}/layouts`);

  await generateIndexPage(srcPath, config);
  await generateLayout(srcPath, config);
  await generateComponent(srcPath, config);
  await generateAstroConfig(projectPath, config);
  await generateTsConfig(projectPath, config);
  await generateViteConfig(projectPath, config);
  await generateGitIgnore(projectPath);

  if (config.frontend.cssFramework === "tailwind") {
    await generateTailwindConfig(projectPath, config);
    await generatePostCSSConfig(projectPath, config);
    await generateGlobalStyles(srcPath, config);
  }

  if (config.frontend.uiComponents === "shadcn") {
    await generateShadcnUtils(srcPath, config);
  }

  if (config.frontend.testing !== "none") {
    await generateVitestConfig(projectPath, config);
    if (config.frontend.testing === "playwright" || config.frontend.testing === "both") {
      await generatePlaywrightConfig(projectPath, config);
    }
  }

  if (config.frontend.eslint) {
    await generateEslintConfig(projectPath, config);
  }

  if (config.frontend.prettier) {
    await generatePrettierConfig(projectPath, config);
  }

  logSuccess(`Astro frontend generated`);
}

async function generateIndexPage(srcPath: string, config: GeneratorConfig): Promise<void> {
  const content = `---
import Layout from '../layouts/Layout.astro';
import Card from '../components/Card.astro';
---

<Layout title="Welcome to ${config.projectName}">
  <main>
    <h1>Welcome to ${config.projectName}</h1>
    <p>This project was generated by Phos 🚀</p>
    <Card title="Getting Started" description="Edit src/pages/index.astro to get started" />
  </main>
</Layout>

<style>
  main {
    padding: 2rem;
    max-width: 800px;
    margin: 0 auto;
  }
  h1 {
    font-size: 2.5rem;
    margin-bottom: 1rem;
  }
</style>
`;

  await writeFile(`${srcPath}/pages/index.astro`, content);
}

async function generateLayout(srcPath: string, config: GeneratorConfig): Promise<void> {
  const content = `---
interface Props {
  title: string;
}

const { title } = Astro.props;
---

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
    <meta name="generator" content={Astro.generator} />
    <title>{title}</title>
  </head>
  <body>
    <slot />
  </body>
</html>

<style is:global>
  * {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
  }
  body {
    font-family: system-ui, -apple-system, sans-serif;
    line-height: 1.5;
  }
</style>
`;

  await writeFile(`${srcPath}/layouts/Layout.astro`, content);
}

async function generateComponent(srcPath: string, config: GeneratorConfig): Promise<void> {
  const content = `---
interface Props {
  title: string;
  description: string;
}

const { title, description } = Astro.props;
---

<div class="card">
  <h2>{title}</h2>
  <p>{description}</p>
</div>

<style>
  .card {
    border: 1px solid #ccc;
    border-radius: 8px;
    padding: 1.5rem;
    margin-top: 2rem;
    background: white;
  }
  .card h2 {
    margin-bottom: 0.5rem;
  }
</style>
`;

  await writeFile(`${srcPath}/components/Card.astro`, content);
}

async function generateAstroConfig(projectPath: string, config: GeneratorConfig): Promise<void> {
  const content = `import { defineConfig } from 'astro/config';

export default defineConfig({
  ${config.frontend.typescript ? "" : "// "}typescript: {
    strict: true,
  ${config.frontend.typescript ? "" : "}"}
  ${config.frontend.cssFramework === "tailwind" ? "integrations: [tailwind()],\n  " : ""}
  ${config.frontend.testing === "vitest" || config.frontend.testing === "both" ? 'vite: {\n    test: {\n      include: ["./src/**/*.{test,spec}.{js,jsx,ts,tsx}"],\n    },\n  },\n  ' : ""}
});
`;

  await writeFile(`${projectPath}/astro.config.mjs`, content);
}

async function generateTsConfig(projectPath: string, config: GeneratorConfig): Promise<void> {
  if (!config.frontend.typescript) return;

  const content = JSON.stringify(
    {
      extends: "astro/tsconfigs/strict",
      compilerOptions: {
        jsx: "react-jsx",
        jsxImportSource: "react",
      },
    },
    null,
    2
  );

  await writeFile(`${projectPath}/tsconfig.json`, content);
}

async function generateViteConfig(projectPath: string, config: GeneratorConfig): Promise<void> {
  const content = `import { defineConfig } from 'vite';

export default defineConfig({
  ${config.frontend.testing === "vitest" || config.frontend.testing === "both" ? 'test: {\n    globals: true,\n    environment: "jsdom",\n  },\n' : ""}
});
`;

  await writeFile(`${projectPath}/vite.config.ts`, content);
}

async function generateTailwindConfig(projectPath: string, config: GeneratorConfig): Promise<void> {
  const content = `/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {},
  },
  plugins: [],
};
`;

  await writeFile(`${projectPath}/tailwind.config.mjs`, content);
}

async function generatePostCSSConfig(projectPath: string, config: GeneratorConfig): Promise<void> {
  const content = `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`;

  await writeFile(`${projectPath}/postcss.config.cjs`, content);
}

async function generateGlobalStyles(srcPath: string, config: GeneratorConfig): Promise<void> {
  const content = `@tailwind base;
@tailwind components;
@tailwind utilities;
`;

  await writeFile(`${srcPath}/styles/global.css`, content);
}

async function generateShadcnUtils(srcPath: string, config: GeneratorConfig): Promise<void> {
  await createDirectory(`${srcPath}/lib`);
  const content = `import { type ClassValue, clsx } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
`;
  await writeFile(`${srcPath}/lib/utils.ts`, content);
}

async function generateVitestConfig(projectPath: string, config: GeneratorConfig): Promise<void> {
  const content = `import { defineConfig } from 'vitest/config';
import astro from '@astrojs/vitest';

export default defineConfig({
  plugins: [astro()],
  test: {
    include: ['src/**/*.{test,spec}.{js,jsx,ts,tsx}'],
  },
});
`;

  await writeFile(`${projectPath}/vitest.config.ts`, content);
}

async function generatePlaywrightConfig(
  projectPath: string,
  config: GeneratorConfig
): Promise<void> {
  const content = `import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './e2e',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',
  use: {
    baseURL: 'http://localhost:4321',
    trace: 'on-first-retry',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
  webServer: {
    command: 'npm run preview',
    url: 'http://localhost:4321',
    reuseExistingServer: !process.env.CI,
  },
});
`;

  await writeFile(`${projectPath}/playwright.config.ts`, content);
}

async function generateEslintConfig(projectPath: string, config: GeneratorConfig): Promise<void> {
  if (!config.frontend.eslint) return;

  const content = `import astroEslint from 'astro-eslint-parser';
import eslintPluginAstro from 'eslint-plugin-astro';

export default [
  {
    files: ['*.astro'],
    languageOptions: {
      parser: astroEslint,
      parserOptions: {
        parser: '@typescript-eslint/parser',
        extraFileExtensions: ['.astro'],
      },
    },
    rules: {
      'astro/no-set-html-directive': 'error',
    },
  },
  {
    ignores: ['dist', 'node_modules', '.astro'],
  },
];
`;

  await writeFile(`${projectPath}/eslint.config.js`, content);
}

async function generatePrettierConfig(projectPath: string, config: GeneratorConfig): Promise<void> {
  if (!config.frontend.prettier) return;

  const content = JSON.stringify(
    {
      semi: false,
      singleQuote: true,
      tabWidth: 2,
      trailingComma: "es5",
      printWidth: 80,
      plugins: ["prettier-plugin-astro"],
      overrides: [
        {
          files: "*.astro",
          options: {
            parser: "astro",
          },
        },
      ],
    },
    null,
    2
  );

  await writeFile(`${projectPath}/.prettierrc`, content);
}

async function generateGitIgnore(projectPath: string): Promise<void> {
  const content = `node_modules/
dist/
.astro/
.env
`;
  await writeFile(`${projectPath}/.gitignore`, content);
}
