import { createDirectory, writeFile, logSuccess, type GeneratorConfig } from "@/utils/helpers.js";

export async function generateNextJSFrontend(
  projectPath: string,
  config: GeneratorConfig
): Promise<void> {
  const srcPath = `${projectPath}/src`;
  await createDirectory(srcPath);
  await createDirectory(`${srcPath}/app`);
  await createDirectory(`${srcPath}/components`);

  await generatePage(srcPath, config);
  await generateLayout(srcPath, config);
  await generateComponent(srcPath, config);
  await generateNextConfig(projectPath, config);
  await generateTsConfig(projectPath, config);
  await generateGitIgnore(projectPath);

  if (config.frontend.cssFramework === "tailwind") {
    await generateTailwindConfig(projectPath, config);
    await generatePostCSSConfig(projectPath, config);
    await generateGlobalStyles(srcPath, config);
  }

  if (config.frontend.uiComponents === "shadcn") {
    await generateShadcnUtils(srcPath, config);
  }

  if (config.frontend.testing !== "none") {
    await generateVitestConfig(projectPath, config);
    if (config.frontend.testing === "playwright" || config.frontend.testing === "both") {
      await generatePlaywrightConfig(projectPath, config);
    }
  }

  if (config.frontend.eslint) {
    await generateEslintConfig(projectPath, config);
  }

  if (config.frontend.prettier) {
    await generatePrettierConfig(projectPath, config);
  }

  logSuccess(`Next.js frontend generated`);
}

async function generatePage(srcPath: string, config: GeneratorConfig): Promise<void> {
  const content = `${config.frontend.typescript ? "import Card from '@/components/Card';\n" : ""}export default function Home() {
  return (
    <main>
      <h1>Welcome to ${config.projectName}</h1>
      <p>This project was generated by Phos 🚀</p>
      <Card title="Getting Started" description="Edit src/app/page.tsx to get started" />
    </main>
  );
}
`;

  await writeFile(`${srcPath}/app/page.${config.frontend.typescript ? "tsx" : "jsx"}`, content);
}

async function generateLayout(srcPath: string, config: GeneratorConfig): Promise<void> {
  const content = `import './globals.css';

export const metadata = {
  title: '${config.projectName}',
  description: 'Generated by Phos',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;

  await writeFile(`${srcPath}/app/layout.${config.frontend.typescript ? "tsx" : "jsx"}`, content);
}

async function generateComponent(srcPath: string, config: GeneratorConfig): Promise<void> {
  const type = config.frontend.typescript
    ? `interface CardProps {
  title: string;
  description: string;
}

export default function Card({ title, description }: CardProps) {`
    : `export default function Card({ title, description }) {`;

  const content = `${type}
  return (
    <div className="card">
      <h2>{title}</h2>
      <p>{description}</p>
    </div>
  );
}
`;

  await writeFile(
    `${srcPath}/components/Card.${config.frontend.typescript ? "tsx" : "jsx"}`,
    content
  );
}

async function generateNextConfig(projectPath: string, config: GeneratorConfig): Promise<void> {
  const content = `/** @type {import('next').NextConfig} */
const nextConfig = {};

export default nextConfig;
`;

  await writeFile(
    `${projectPath}/next.config.${config.frontend.typescript ? "js" : "js"}`,
    content
  );
}

async function generateTsConfig(projectPath: string, config: GeneratorConfig): Promise<void> {
  if (!config.frontend.typescript) return;

  const content = JSON.stringify(
    {
      compilerOptions: {
        target: "ES2017",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: {
          "@/*": ["./src/*"],
        },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    },
    null,
    2
  );

  await writeFile(`${projectPath}/tsconfig.json`, content);
}

async function generateTailwindConfig(projectPath: string, config: GeneratorConfig): Promise<void> {
  const content = `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
`;

  await writeFile(`${projectPath}/tailwind.config.js`, content);
}

async function generatePostCSSConfig(projectPath: string, config: GeneratorConfig): Promise<void> {
  const content = `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`;

  await writeFile(`${projectPath}/postcss.config.js`, content);
}

async function generateGlobalStyles(srcPath: string, config: GeneratorConfig): Promise<void> {
  const content = `@tailwind base;
@tailwind components;
@tailwind utilities;

* {
  box-sizing: border-box;
}
body {
  font-family: system-ui, -apple-system, sans-serif;
  line-height: 1.5;
}

main {
  padding: 2rem;
  max-width: 800px;
  margin: 0 auto;
}

h1 {
  font-size: 2.5rem;
  margin-bottom: 1rem;
}

.card {
  border: 1px solid #ccc;
  border-radius: 8px;
  padding: 1.5rem;
  margin-top: 2rem;
  background: white;
}
`;

  await writeFile(`${srcPath}/app/globals.css`, content);
}

async function generateShadcnUtils(srcPath: string, config: GeneratorConfig): Promise<void> {
  await createDirectory(`${srcPath}/lib`);
  const content = `import { type ClassValue, clsx } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
`;
  await writeFile(`${srcPath}/lib/utils.${config.frontend.typescript ? "ts" : "js"}`, content);
}

async function generateVitestConfig(projectPath: string, config: GeneratorConfig): Promise<void> {
  const content = `import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  test: {
    include: ['src/**/*.{test,spec}.{js,jsx,ts,tsx}'],
    environment: 'jsdom',
  },
});
`;

  await writeFile(`${projectPath}/vitest.config.ts`, content);
}

async function generatePlaywrightConfig(
  projectPath: string,
  config: GeneratorConfig
): Promise<void> {
  const content = `import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './e2e',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',
  use: {
    baseURL: 'http://localhost:3000',
    trace: 'on-first-retry',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
  webServer: {
    command: 'npm run dev',
    url: 'http://localhost:3000',
    reuseExistingServer: !process.env.CI,
  },
});
`;

  await writeFile(`${projectPath}/playwright.config.ts`, content);
}

async function generateEslintConfig(projectPath: string, config: GeneratorConfig): Promise<void> {
  if (!config.frontend.eslint) return;

  const content = `module.exports = {
  root: true,
  extends: ['next/core-web-vitals', 'prettier'],
  rules: {
    '@typescript-eslint/no-unused-vars': 'warn',
  },
};
`;

  await writeFile(`${projectPath}/.eslintrc.json`, content);
}

async function generatePrettierConfig(projectPath: string, config: GeneratorConfig): Promise<void> {
  if (!config.frontend.prettier) return;

  const content = JSON.stringify(
    {
      semi: false,
      singleQuote: true,
      tabWidth: 2,
      trailingComma: "es5",
      printWidth: 80,
    },
    null,
    2
  );

  await writeFile(`${projectPath}/.prettierrc`, content);
}

async function generateGitIgnore(projectPath: string): Promise<void> {
  const content = `node_modules/
.next/
.vercel/
.env
*.log
`;
  await writeFile(`${projectPath}/.gitignore`, content);
}
