import { createDirectory, writeFile, logSuccess, type GeneratorConfig } from "@/utils/helpers.js";

export async function generateSvelteFrontend(
  projectPath: string,
  config: GeneratorConfig
): Promise<void> {
  const srcPath = `${projectPath}/src`;
  await createDirectory(srcPath);
  await createDirectory(`${srcPath}/routes`);
  await createDirectory(`${srcPath}/lib`);

  await generateAppHtml(projectPath, config);
  await generateIndexPage(srcPath, config);
  await generateLayout(srcPath, config);
  await generateComponent(srcPath, config);
  await generateSvelteConfig(projectPath, config);
  await generateViteConfig(projectPath, config);
  await generateTsConfig(projectPath, config);
  await generateGitIgnore(projectPath);

  if (config.frontend.cssFramework === "tailwind") {
    await generateTailwindConfig(projectPath, config);
    await generatePostCSSConfig(projectPath, config);
    await generateGlobalStyles(srcPath, config);
  }

  if (config.frontend.uiComponents === "shadcn") {
    await generateShadcnUtils(srcPath, config);
  }

  if (config.frontend.testing !== "none") {
    await generateVitestConfig(projectPath, config);
    if (config.frontend.testing === "playwright" || config.frontend.testing === "both") {
      await generatePlaywrightConfig(projectPath, config);
    }
  }

  if (config.frontend.eslint) {
    await generateEslintConfig(projectPath, config);
  }

  if (config.frontend.prettier) {
    await generatePrettierConfig(projectPath, config);
  }

  logSuccess(`Svelte frontend generated`);
}

async function generateAppHtml(projectPath: string, config: GeneratorConfig): Promise<void> {
  const content = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" href="%sveltekit.assets%/favicon.png" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    %sveltekit.head%
  </head>
  <body data-sveltekit-preload-data="hover">
    <div style="display: contents">%sveltekit.body%</div>
  </body>
</html>
`;

  await writeFile(`${projectPath}/src/app.html`, content);
}

async function generateIndexPage(srcPath: string, config: GeneratorConfig): Promise<void> {
  const content = `<script>
  import Card from '$lib/components/Card.svelte';
</script>

<svelte:head>
  <title>Welcome to ${config.projectName}</title>
</svelte:head>

<main>
  <h1>Welcome to ${config.projectName}</h1>
  <p>This project was generated by Phos 🚀</p>
  <Card title="Getting Started" description="Edit src/routes/+page.svelte to get started" />
</main>

<style>
  main {
    padding: 2rem;
    max-width: 800px;
    margin: 0 auto;
  }
  h1 {
    font-size: 2.5rem;
    margin-bottom: 1rem;
  }
</style>
`;

  await writeFile(`${srcPath}/routes/+page.svelte`, content);
}

async function generateLayout(srcPath: string, config: GeneratorConfig): Promise<void> {
  const content = `<script>
  import '../app.css';
</script>

<slot />
`;

  await writeFile(`${srcPath}/routes/+layout.svelte`, content);
}

async function generateComponent(srcPath: string, config: GeneratorConfig): Promise<void> {
  await createDirectory(`${srcPath}/lib/components`);

  const content = `<script>
  let { title, description } = $props();
</script>

<div class="card">
  <h2>{title}</h2>
  <p>{description}</p>
</div>

<style>
  .card {
    border: 1px solid #ccc;
    border-radius: 8px;
    padding: 1.5rem;
    margin-top: 2rem;
    background: white;
  }
  .card h2 {
    margin-bottom: 0.5rem;
  }
</style>
`;

  await writeFile(`${srcPath}/lib/components/Card.svelte`, content);
}

async function generateSvelteConfig(projectPath: string, config: GeneratorConfig): Promise<void> {
  const content = `import adapter from '@sveltejs/adapter-auto';
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  preprocess: vitePreprocess(),
  kit: {
    adapter: adapter(),
  },
  ${config.frontend.typescript ? "" : "// "}typescript: {
    config(config) {
      const { compilerOptions } = config;

      compilerOptions.typescript = {
        ...(compilerOptions.typescript ?? {}),
        strict: true,
      };

      return config;
    }
  ${config.frontend.typescript ? "" : "}"}
};

export default config;
`;

  await writeFile(`${projectPath}/svelte.config.js`, content);
}

async function generateViteConfig(projectPath: string, config: GeneratorConfig): Promise<void> {
  const content = `import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

export default defineConfig({
  plugins: [sveltekit()],
  ${config.frontend.testing === "vitest" || config.frontend.testing === "both" ? 'test: {\n    globals: true,\n    environment: "jsdom",\n  },\n' : ""}
});
`;

  await writeFile(`${projectPath}/vite.config.js`, content);
}

async function generateTsConfig(projectPath: string, config: GeneratorConfig): Promise<void> {
  if (!config.frontend.typescript) return;

  const content = JSON.stringify(
    {
      extends: "./.svelte-kit/tsconfig.json",
      compilerOptions: {
        allowJs: true,
        checkJs: true,
        esModuleInterop: true,
        forceConsistentCasingInFileNames: true,
        resolveJsonModule: true,
        skipLibCheck: true,
        sourceMap: true,
        strict: true,
      },
    },
    null,
    2
  );

  await writeFile(`${projectPath}/tsconfig.json`, content);
}

async function generateTailwindConfig(projectPath: string, config: GeneratorConfig): Promise<void> {
  const content = `/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  theme: {
    extend: {},
  },
  plugins: [],
};
`;

  await writeFile(`${projectPath}/tailwind.config.js`, content);
}

async function generatePostCSSConfig(projectPath: string, config: GeneratorConfig): Promise<void> {
  const content = `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`;

  await writeFile(`${projectPath}/postcss.config.cjs`, content);
}

async function generateGlobalStyles(srcPath: string, config: GeneratorConfig): Promise<void> {
  const content = `@tailwind base;
@tailwind components;
@tailwind utilities;

* {
  box-sizing: border-box;
}
body {
  font-family: system-ui, -apple-system, sans-serif;
  line-height: 1.5;
}
`;

  await writeFile(`${srcPath}/app.css`, content);
}

async function generateShadcnUtils(srcPath: string, config: GeneratorConfig): Promise<void> {
  const content = `import { type ClassValue, clsx } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
`;
  await writeFile(`${srcPath}/lib/utils.ts`, content);
}

async function generateVitestConfig(projectPath: string, config: GeneratorConfig): Promise<void> {
  const content = `import { defineConfig } from 'vitest/config';
import { svelte } from '@sveltejs/vite-plugin-svelte';

export default defineConfig({
  plugins: [svelte({ hot: !process.env.VITEST })],
  test: {
    include: ['src/**/*.{test,spec}.{js,ts}'],
    environment: 'jsdom',
  },
});
`;

  await writeFile(`${projectPath}/vitest.config.js`, content);
}

async function generatePlaywrightConfig(
  projectPath: string,
  config: GeneratorConfig
): Promise<void> {
  const content = `import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests/e2e',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',
  use: {
    baseURL: 'http://localhost:4173',
    trace: 'on-first-retry',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
  webServer: {
    command: 'npm run preview',
    url: 'http://localhost:4173',
    reuseExistingServer: !process.env.CI,
  },
});
`;

  await writeFile(`${projectPath}/playwright.config.ts`, content);
}

async function generateEslintConfig(projectPath: string, config: GeneratorConfig): Promise<void> {
  if (!config.frontend.eslint) return;

  const content = `export default {
  root: true,
  extends: ['eslint:recommended'],
  parserOptions: {
    sourceType: 'module',
    ecmaVersion: 2020,
    extraFileExtensions: ['.svelte'],
  },
  env: {
    browser: true,
    es2017: true,
    node: true,
  },
  overrides: [
    {
      files: ['*.svelte'],
      parser: 'svelte-eslint-parser',
      parserOptions: {
        parser: '@typescript-eslint/parser',
      },
    },
  ],
};
`;

  await writeFile(`${projectPath}/.eslintrc.cjs`, content);
}

async function generatePrettierConfig(projectPath: string, config: GeneratorConfig): Promise<void> {
  if (!config.frontend.prettier) return;

  const content = JSON.stringify(
    {
      semi: false,
      singleQuote: true,
      tabWidth: 2,
      trailingComma: "es5",
      printWidth: 80,
      plugins: ["prettier-plugin-svelte"],
      overrides: [
        {
          files: "*.svelte",
          options: {
            parser: "svelte",
          },
        },
      ],
    },
    null,
    2
  );

  await writeFile(`${projectPath}/.prettierrc`, content);
}

async function generateGitIgnore(projectPath: string): Promise<void> {
  const content = `node_modules/
.DS_Store
dist/
.svelte-kit/
.vercel/
.env
`;
  await writeFile(`${projectPath}/.gitignore`, content);
}
